### ISSUE TITLE
Build: Package fails to install on node 0.12 because of dependency on node-syslog

### ISSUE THREAD

**Issue by gabrielschulhof** [scottgonzalez/simple-log#3]
strong-fork-syslog is a fork of node-syslog in response to it not having received updates on npm in a while. It builds successfully on both node 0.10 and 0.12.

**Comment by gabrielschulhof** [comment]
https://github.com/schamane/node-syslog/issues/37#issuecomment-67091987

**Comment by gabrielschulhof** [comment]
@schamane has released a new version of node-syslog, so I modified the PR (#4) to use that instead.

**Comment by gabrielschulhof** [comment]
I've tested it with both node v0.10 and v0.12 and it builds on both.

**Comment by scottgonzalez** [comment]
Released as v1.2.0. Thanks!
